name: Frontend S3 deployment

on:
  push:
    paths:
      - "client/**"
      - "frontend.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          cd client
          npm client
          npm run build

      - name: Sync to S3
        run: aws s3 sync client/build/
